### PR TITLE
Add lz4 compress

### PR DESCRIPTION
**Pull request by cavazquez**

### CODE REVIEW

**Comment by fdupoux** [comment]
Thanks for your Pull Request. It can be considered as the risk of introducing regression is quite low.
- You will need to update the .travis.yml file so it installs liblz4-dev in order to fix the test
https://packages.ubuntu.com/trusty/liblz4-dev
- There are things to be fixed in the code such as PKG_CHECK_MODULES([LZMA], [liblz4])
- We need to find a consistent approach for the compression levels

Regarding compression levels it sounds strange that level 10 would be much weaker than level 9 as people would expect higher numbers to correspond to better compression ratios. But on the other hand we do not want to change the behaviors for existing numbers as it would upset users who are using it in their scripts.

I think the best approach is to keep single digit compression levels as they currently are and to introduce a double digit scheme in parallel to the existing one:
- Levels 0 to 9 would correspond to the existing scheme
- Levels 20 to 29 would correspond to LZO levels 0 to 9
- Levels 31 to 39 would correspond to LZ4 levels 0 to 9
- Levels 51 to 59 would correspond to GZIP levels 0 to 9
- Levels 61 to 69 would correspond to BZIP2 levels 0 to 9
- Levels 81 to 89 would correspond to XZ levels 0 to 9
- The gaps would allow support for future compression algorithms

**Comment by cavazquez** [comment]
Fail only in Ubuntu Trusty. In Ubuntu Xenial and Archlinux it works.

**Comment by fdupoux** [comment]
fsarchiver needs to keep working on older Linux distributions so this should be fixed to work on Ubuntu Trusty.

**Comment by fdupoux** [comment]
Thanks for having made it build successfully on Ubuntu 14.04.

I have done a code review and found the following issues:
- The LZ4 compression and decompression are implemented but are never used by the program. Running fsarchiver with -z10 causes it to hang so the change has apparently not been tested.
- The build will fail if support for LZ4 is disabled on a system where lz4 is not installed as lz4 is always built
- The build prints warnings saying LZ4_compress is deprecated when fsarchiver is built with the latest lz4. The solution is to use "#if LZ4_VERSION_NUMBER >= XXX" to use the new LZ4 functions with LZ4 versions which provide the new functions and to use the old function with old LZ4 versions
- It does not make sense to use a switch statement with only a single case. A regular if/else should be used instead to deal with success (res > 0) and failure.
- The compression and decompression function must return an accurate status. They must only return FSAERR_ENOMEM if the failure is caused by an out of memory error
- The errprintf() messages need to show the correct name of the function which have failed 
- The diff shows there are changes which are isolated spaces or newlines changes in some places. These changes must be removed so only the actual code changes remain.

After these issues have been addressed the -z option will need to be changed so compression levels are consistent. One approach is to provide double digit compression levels as detailed in previous comments.

**Comment by cavazquez** [comment]
HI! I fix the above items. The compression level could be a string with number, example:  -b lz4  -l 3 or -b bzip2 -3 ?

**Comment by fdupoux** [comment]
Again the switch statement in comp_lz4.c does not make any sense as there is no case statement. And the compiler you the code in the switch statement is never going to be executed:
```
comp_lz4.c: In function ‘compress_block_lz4’:
comp_lz4.c:39:11: warning: statement will never be executed [-Wswitch-unreachable]
         if(res == 0){
           ^
```
You have copied and pasted the code from the bzip2 implementation, but the error handling is incorrect. There is nothing in the LZ4 documentation which says that a return status equal to zero corresponds to a memory error. It can correspond to any failure. You can find these details in lz4.h. As both types of compression functions use return status equal to zero to indicate an error there should be a single piece of code to handle the success or error of the compression functions, and the error message needs to be accurate. Same thing with the decompression code.

The compression level will need to be modified after all the implementation is completed properly. For now we should probably use level 0 instead of level 10 for LZ4 as the higher the number the higher the compression is expected to be, so level 10 is expected to be even better than LZMA/XZ. As level 0 is currently not in use it would make more sense to use it for a fast compression algorithm.

**Comment by cavazquez** [comment]
I fix switch/if . 
Should I create new states? or only use FSERR_UNKNOWN?
New error: 
It only happens with lz4:  oper_restore.c#709,extractar_restore_obj_regfile_multi(): cannot restore file test/hola, the data block (which is shared by multiple files) is corrupt . 
I keep investigating

**Comment by fdupoux** [comment]
Yes that is better. The FSAERR_UNKNOWN code is ok for general errors when we do not know the reason for a failure.

In the compression code there is no need to use an if after the #if #endif block, as you have already considered the case of a failure (when res==0). So the compression has been successful past this point and it should always return FSAERR_SUCCESS

There should be a single if statement in the decompression code as there are only two possibilities. Either the function returns a negative result and it is a failure or it is successful.

**Comment by fdupoux** [comment]
Apparently you have passed the arguments in the wrong order in LZ4_compress_default() as the documentation says the first argument it the source and the second one is the destination.

Another problem is the size of the output data need to be set properly for both compression and decompression. At the moment you just set these to the size of the allocated buffer and just leave it like that. The fsarchiver core needs to know how many bytes were actually returned during compression or decompression so it can write the appropriate data to the output files.

**Comment by cavazquez** [comment]
Hi! I made performance graphics

compress

decompress

size

performance

**Comment by fdupoux** [comment]
The enum which defines COMPRESS_LZ4 needs to be modified as COMPRESS_LZ4 has been added in the third position which means that it changes the numbers allocated to other compression algorithms and hence the numbers are not going to match what was defined in previous fsarchiver versions so it breaks compatibility.

**Comment by cavazquez** [comment]
ok. But What is the correct position? I dont have 0 because 0 is COMPRESS_NULL.

**Comment by fdupoux** [comment]
It needs to be added at the very end of the list otherwise it modified the values of existing entries in the list

**Pull request merged**
